### ISSUE TITLE
Adding Seatalk 1 interface electronics 

### ISSUE THREAD

**Issue by DavidCBarrett** [miniwinwm/BlueBridge#1]
Hi Angus, i've just discovered your various amazing projects - great work!. I understand BlueBridge is your latest and active one. 

It would be great if you wouldn't mind adding the electronics interface for us boaters still invested in Seatalk 1 instruments. Hopefully this is just a lift and shift of the bi-directioanl Seatalk interfaces from your previous projects (i'm assuming there are ports available on the micro controller and your bit-banging methods could be used on the ESP32). Users can then add the Seatalk 1 componets to the PCB if they need. Software can be added over time by you or others if you don't feel like it.

Thanks and Kind Regards,  David Barrett.

**Comment by miniwinwm** [comment]
Hi David

Thanks for your feedback. I'm between boats and my new one won't have that
network on it. That's the reason that I haven't added it because I have no
need now, and also no Seatalk 1 network to test it on. If it was to be
added the software would not be a problem. Much of the old code could be
ported. The ESP32 runs FreeRTOS which doesn't have a quick enough tick
period to bit bang at 4800 baud so interrupts would be needed. For the
hardware the main problem is lack of space on the board. There are port
pins available. It would be easier for Seatalk 1 read only as that requires
less components. Referring to the layout BlueBridge.pcb file it may be
possible to squeeze them in...

- Another connector would need adding. TP1 could be removed or moved - it's
only a test point. If C3 and U4 were moved to the right there would be
space for another connector next to the 12V and GND connectors
- The space on the rhs of the board needs to be kept clear as the sockets
overhang here, but TP1 could go there
- R3 and R9 could go under the power supply board
- GND/B and RXD/A connectors could then be moved to the right
- R8 and additional resistors could go under U1. This is possible to build
but DesignSpark moans about component clashes

That would free up space to the right of U1 for the Seatalk 1 interface
components.

This project is on hold at the moment as it can't be tested on a real
boat's system until I get a boat. I may add the Seatalk 1 read only
interface if I have time. I'll let you know progress. I'm happy for anyone
to fork the project in github as well.

AMcD

**Comment by miniwinwm** [comment]
Seatalk 1 is not going to be added to this project as I have no Seatalk 1 instruments on my boat any more.
